---

name: PerlSec Scan
description: Security scan for Perl files
inputs:
  args:
    description: Arguments to pass to perlsec-scan
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        git clone https://github.com/nigelhorne/perlsec-scanner.git
        cd perlsec-scanner && cpanm --installdeps .
        perl bin/perlsec-scan ${{ inputs.args }}
      shell: bash
