name: PerlSec Scanner

on:
  push:
    paths:
      - '**.pl'
      - 'lib/**'
      - 'allowed_modules.txt'
  pull_request:
    paths:
      - '**.pl'
      - 'lib/**'
      - 'allowed_modules.txt'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.36'

    - name: Install dependencies
      run: cpan install JSON

    - name: Run PerlSec Scanner
      run: perl scan.pl > findings.json

    - name: Annotate findings (optional)
      if: ${{ always() }}
      run: |
        cat findings.json
