name: Run Perl Tests

permissions:
  contents: read

on:
  push:
    paths:
      - '**.pl'
      - 'lib/**'
      - 'bin/**'
      - 't/**'
      - 'Makefile.PL'
  pull_request:
    paths:
      - '**.pl'
      - 'lib/**'
      - 'bin/**'
      - 't/**'
      - 'Makefile.PL'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl: ['5.36', '5.38']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Perl ${{ matrix.perl }}
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: Install dependencies
      run: |
        cpanm --installdeps .
        cpanm --iqn Test::DescribeMe

    - name: Run tests
      run: prove -l t/
